### ISSUE TITLE
Server crash 

### ISSUE THREAD

**Issue by outlawtorn** [papandreou/express-processimage#198] opened 2023-12-08 12:45 UTC
Hi,

We are experiencing server crash due to "cannot read property of undefined".
We are using v10.3.0 and node.js v18.16.0

![gifsicle_error](https://github.com/papandreou/express-processimage/assets/3257189/34c159c1-13e2-44d3-bccc-03646d82e3e6)

@alexjeffburke can you please have a look? 

Thank you very much.

**Comment by alexjeffburke** [comment] 2023-12-11 13:48
Hi @outlawtorn

First, as we’d request with any such report, could you please look at providing a (ideally minimal) reproduction? The stack trace you’ve pasted is not enough to identify the why of what’s happening. This could take the form of an image file that triggers this problem, or at the very least detailing the input image type and the conversion options that were requested.

Second, and for future reference: this is an open source project to which I give my time voluntarily. I am sympathetic to your production issue, and I am sorry you’ve hit a problem with the package, but pinging me directly in this fashion is a bit forceful. If your organisation needs direct access to me at short notice I would be happy to discuss paid support, alternatively committing some time toward the effort of tracking down the cause would definitely aid getting this fixed sooner. PRs are also welcome. Otherwise I will get to it as and when time permits.

Thanks, Alex J Burke.

**Comment by outlawtorn** [comment] 2023-12-11 15:10
Hi @alexjeffburke ,

Thank you for giving your time and support.
I apologies on directly pinging you.
I reason why I directly ping you is because it is related to the latest update(v10.3.0) you have done and impro(v0.13.1).

As for the the image input file that caused this is a gif file.
Unfortunately the gif file was deleted and I have no way to ask our customer for the file.

Thank you for again and I will update this will sample input file as soon this error occurs again.

Warm regards,
Alexader Soriano

**Comment by alexjeffburke** [comment] 2023-12-12 13:15
Hi,

Thanks for the response.

Ok, so the original file is gone but _might_ be a GIF - that's unfortunate but as it goes. Would you able to get me the conversion options that we're requested? Also, can you provide more detail around how you're using the module... is it being exposed by mounting it directly as a middleware or are you doing something more custom that might be relevant?

The problem I'm facing from a maintainer perspective is my last attempt to fix an issue without a user-supplied reproduction was the last release, and now it seems there is another report that looks somewhat related, so I'm a bit hesitant to continue down a rabbit hole of chasing fixes "blind" for a situation whose cause I don't quite understand.

Let me share my hunch: my guess is that you might have users supplying bogus files for conversion. Specifically I'd bet something like `express-processimage` either detects (file extension from request path) or is being instructed to operate on a GIF but there is something wrong with the content, perhaps the image "file" (in quotes because we're really dealing with streams here) is either empty or not actually a GIF and then Gifsicle blows up. If so, I'd really like to get this down to a test case. Have you had any luck reproducing the issue? If not, could I ask you to try the two cases I mentioned (empty file, non GIF file with a GIF extension) against `express-processimage` in your environment ands see if the problem happens?

Thanks, Alex J Burke.

**Comment by outlawtorn** [comment] 2023-12-19 09:15
Hi,

We are using it as middleware
`
const makeExpressProcessImageMiddleware = (config/*: Object */) => require('express-processimage')({
    maxOutputPixels: config.imageScaleMaxPixels,
    maxInputPixels: config.imageScaleMaxPixels,
    allowedImageSourceContentTypes: config.allowedImageSourceContentTypes,
    sharpCache: false,
    sharpFailOnError: false,
    secondGuessSourceContentType: true,
    allowOperation: operationName => config.allowedImageOperations.indexOf(operationName) !== -1,
});

// allowed content types
[
    "image/png",
    "image/jpeg",
    "image/gif",
    "image/webp"
]

// allowed operation
[
    "withoutEnlargement",
    "ignoreAspectRatio",
    "interpolateWith",
    "metadata",
    "resize",
    "extract",
    "crop",
    "rotate",
    "quality",
    "format",
    "png",
    "jpeg",
    "gm"
]
`
I was not able to reproduce it even with production data.
But I was able to reproduce it by forcing the error to emit in node_modules/gifsicle-stream/lib/Gifsicle.js

`
Gifsicle.prototype.write = function(chunk) {
...
        this.process.stdout
          .on('data', function(chunk) {
            this.seenOutput = true;
            this.emit('data', chunk);
          }.bind(this))
          .on('end', function() {

            this._error(new Error('Gifsicle: STDOUT stream ended without emitting any data.'));
            
            // if (!this.finished) {
            //   if (this.seenOutput) {
            //     this.emit('end');
            //   } else {
            //     this._error(new Error('Gifsicle: STDOUT stream ended without emitting any data.'));
            //   }
            //   this.finished = true;
            // }
          }.bind(this));
`

So the problem is the "this" context is missing in node_modules/express-processimage/node_modules/impro/src/Pipeline.js
so i added

const that = this

`
flush(isStream = false) {
...
      const that = this;
      // protect against filters emitting errors more than once
      stream.once('error', function(err) {
        const engineName = that.usedEngines[i].name;
        let commandArgs;
        if (!(err instanceof Error)) {
          const messageForNonError = `${engineName} emitted non-Error (stream index ${i})`;
          err = new Error(messageForNonError);
          commandArgs = null;
        } else if (err.commandArgs) {
          commandArgs = err.commandArgs;
        } else {
          commandArgs = that.usedEngines[i].commandArgs;
        }
        if (commandArgs) {
          err.commandLine = `${engineName} ${commandArgs.join(' ')}`;
        }
        that._fail(err, true);
      });
`

So now my local server is no longer crashing and the error is handled properly.

Can you please check this if im right?

Thank you,
Alex

**Comment by alexjeffburke** [comment] 2023-12-19 14:08
Hi @outlawtorn,

This detail is rather helpful, thanks for providing it. What I think it has done is provide evidence for a cause though I don't think it's quite the one you suggest. I am now relatively sure it was actually an issue within the `gifsicle-stream` library.

Let me expand. The lines of code you pulled out of `impro` don't exist in the library as you wrote them. The version of `express-processimage` you were running depends on 0.13.1 of `impro`, and there the handler tied to `stream.once()` is an arrow function: https://github.com/papandreou/impro/blob/v0.13.1/src/Pipeline.js#L227. That arrow function is already tightly bound. But there clearly was a problem somewhere with a bad dereference, and you also noted gifsicle use being involved. 

A few days ago it occurred to me that the error message that was reported didn't seem to correspond to anything in `impro` and the stack trace looked like it might be incomplete. But, the error appeared to be bubbling up from `gifsicle-stream` so I started to suspect an issue at that level thus I took a peek under its covers to see how it invokes the gifsicle binary.

In the opening I said it _was_ an issue.. after that inspection I took some preemptive action and replaced `gifsicle-stream`; details contained in commits https://github.com/papandreou/impro/commit/c2f6f5b2ea7248e9f07cb785183294cfa880cff0 and https://github.com/papandreou/impro/commit/b8ec08a5231d18a3e8e5125fe5a2394a40ae868d. This has shipped both as a new `impro` version and a corresponding `express-processimage` release.

Given the rework in this area and the fact the codepaths are somewhat different now I'm going to close this issue out. If anything comes up once you've pulled in the new version please open a separate issue and we can take it from there.

Thanks, Alex J Burke.

**Closed by alexjeffburke** 2023-12-19 14:08 UTC
